name: CI/CD to GitHub Pages

on:
  push:
    branches:
      - main  

jobs:
  build_and_publish_site:
    runs-on: ubuntu-latest
    steps:
      - name: Check recent updates from repository
        uses: actions/checkout@v3

      - name: Check/Store Cached Dependencies
        uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Set Up Ruby v3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 
          bundler-cache: true
      
      - name: Install dependencies & set permissions
        run: |
          bundle exec jekyll build

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1


  deploy_site:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build_and_publish_site
    permissions:
      pages: write 
      id-token: write
    steps:
      - name: Deployment to GitHub Pagess Environment
        id: deployment
        uses: actions/deploy-pages@v2
