name: Continuous Integration / Continuous Deployment to GitHub Pages

on:
  push:
    branches:
      - master  

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check recent updates from repository
        uses: actions/checkout@v3

      - name: Check/Store Cached Dependencies
        uses: actions/cache@v3
          with:
            path: vendor/bundle
            key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
            restore-keys: |
              ${{ runner.os }}-gems-

      - name: Set Up Ruby v3.0.0
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0 
          bundler-cache: true
      
      - name: Install dependencies & set permissions
        run: |
          gem install bundler
          bundle config path vendor/bundle
          bundle install --jobs 4 --retry 3
          bundle exec jekyll build
          chmod a+x bin/*
          git commit -am "add execute permision to bin/deploy"

        - name: Deploy site to Github Pages
          uses: peaceiris/actions-gh-pages@v3
          with:
            github_token: ${{ secrets.GITHUB_TOKEN }}
            publish_dir: ./_site
            publish_branch: gh-pages
